### PR TITLE
Added my self??????

### PR DESCRIPTION
**Pull request by siravijbb**
**Always tag `🚀 READY FOR REVIEW` once your PR is Ready to be one of us :)**

We value your endeavors to enhance the Hacktoberfest Museum better!

## If (this.PR.category === "The new entry 💫")

**Please tag `The new entry 💫` to the PR in order to categorize yours as the star being recognized by the Museum.**

## Else if (this.PR.category === "Enhancement 🛠")

**Please tag `Enhancement 🛠` to the PR as you're developing the Museum more wonderfully!**

## Finally:

> 🪄 **DON'T FORGET TO CLAIM YOUR TICKET!** via [Eventpop application form.](https://www.eventpop.me/events/13854/application_forms/845/applicants/new)

### CODE REVIEW

**Comment by leomotors** [comment]
Conflict

**Review by leomotors — DISMISSED** [review]

**Comment by Gusb3ll** [comment]
Conflict 
image0-2

**Comment by siravijbb** [comment]
`Add more commits by pushing to the [main](https://github.com/siravijbb/hacktoberfest-museum) branch on [siravijbb/hacktoberfest-museum](https://github.com/siravijbb/hacktoberfest-museum).`

Since there was a Conflict,so fixed!!

**Review by leomotors — APPROVED** [review]
มาเพื่อแก้อันนี้อันเดียวเลยหรอ :armweed:

**Review by Gusb3ll — APPROVED** [review]

**Pull request merged**
