### PR TITLE
feat: separate entries to folder

### PR DESCRIPTION
**Pull request by ryanrw**
As project grow, the array will be larger.

I saw @intaniger separate the entries into a new file (in `feat/detail` branch), but it still array type.

That's why I chose to separate them into `.mdx` file in `/entries` folder, which I chose `.mdx` because I thought that we might need Markdown support too.

### CODE REVIEW

**Comment by intaniger** [comment]
That's very cool! I think only changes we need left is new CONTRIBUTING.md, let me writing it.

**Comment by intaniger** [comment]
@ryanrw there are some questions regard to our data structure that need to be concern and find a solution together. 

- does mdx support for nested key-value? as we need `detail: DetailedPageProps` which is sub-tree from `CardProps`
- for `founderName` and `topic`, we have intention to group the same together in order to filter it without duplication, but as far as my little knowledge of mdx, I can't do `import { Founders } from "../enums/founders.enum"` within mdx file. do we need workaround for mdx a little bit?

**Comment by intaniger** [comment]
To be more clear on enum thing. objective of using enum is to eliminate typing invariant like `React.js` or `React` which those two topics should be the same.

**Comment by leomotors** [comment]
not related to this PR but how we end up having double lockfile here???

**Comment by ryanrw** [comment]
> @ryanrw there are some questions regard to our data structure that need to be concern and find a solution together.
> 
> * does mdx support for nested key-value? as we need `detail: DetailedPageProps` which is sub-tree from `CardProps`
> * for `founderName` and `topic`, we have intention to group the same together in order to filter it without duplication, but as far as my little knowledge of mdx, I can't do `import { Founders } from "../enums/founders.enum"` within mdx file. do we need workaround for mdx a little bit?

@intaniger I think nested key is not supported in mdx. And also, I couldn't import the Enum within mdx file as you mention.

Should we switch to TS for `Enum` and nested object support?

**Comment by ryanrw** [comment]
> not related to this PR but how we end up having double lockfile here???

@Leomotors i dunno, maybe we should decide which package manager we want to use?

> One package manager. Many people decided.

image

**Comment by intaniger** [comment]
> > @ryanrw there are some questions regard to our data structure that need to be concern and find a solution together.
> > 
> > * does mdx support for nested key-value? as we need `detail: DetailedPageProps` which is sub-tree from `CardProps`
> > * for `founderName` and `topic`, we have intention to group the same together in order to filter it without duplication, but as far as my little knowledge of mdx, I can't do `import { Founders } from "../enums/founders.enum"` within mdx file. do we need workaround for mdx a little bit?
> 
> @intaniger I think nested key is not supported in mdx. And also, I couldn't import the Enum within mdx file as you mention.
> 
> Should we switch to TS for `Enum` and nested object support?

I think so.

**Comment by intaniger** [comment]
> > not related to this PR but how we end up having double lockfile here???
> 
> @Leomotors i dunno, maybe we should decide which package manager we want to use?
> 
> > One package manager. Many people decided.
> 
> image

currently we're using `npm` please stick to this one for this PR. but further alteration like switching to `pnpm` is sound great as well. but it should be in separated PR

**Comment by ryanrw** [comment]
@intaniger I've changed filetype to `.ts`, please review again na krub.

**Review by dtinth — APPROVED** [review]
Separating into files sounds great because then there is less chance of conflict, let’s get this in!

**Pull request merged**
