### PR TITLE
chore: force everyone to use pnpm because it's better

### PR DESCRIPTION
**Pull request by ryanrw**
As @intaniger decided that we need only one package manager, therefore, I chose to use `npm` and remove `yarn.lock` file.

### CODE REVIEW

**Comment by ryanrw** [comment]
Discussed in PR https://github.com/creatorsgarten/hacktoberfest-museum/pull/13#issuecomment-1287972426

**Comment by ryanrw** [comment]
Build was failed, dunno why 🥲

**Comment by leomotors** [comment]
We need to change them in netlify config too?

**Comment by ryanrw** [comment]
> We need to change them in netlify config too?

Any idea how?

**Comment by dtinth** [comment]
image

**Comment by leomotors** [comment]
Should we skip npm yarn and go with `pnpm`?

**Comment by ryanrw** [comment]
> Should we skip npm yarn and go with `pnpm`?

I think some people is more familiar with `npm` or `yarn`, especially the people who start learning JavaScript.

But it's a great idea to convince them to use better solution like `pnpm`. What do you guys think?

**Comment by ryanrw** [comment]
> image

@dtinth I don't have access to Netlify CI/CD pipeline, and also idk what happen to this one. 😓

**Comment by leomotors** [comment]
> But it's a great idea to convince them to use better solution like pnpm. What do you guys think?

Yes, we should convince them to. To do this, we can put the guide like `npm i -g pnpm` into README and may add `npx only-allow pnpm` to force them to.

**Comment by dtinth** [comment]
Agree, let’s switch to pnpm!

**Comment by dtinth** [comment]
If you need help looking at the build logs, please ping me on Creatorsgarten Discord.

**Comment by ryanrw** [comment]
@dtinth @Leomotors I haven't joined Discord, need help to pull me in krub.

**Comment by ryanrw** [comment]
> @dtinth @Leomotors I haven't joined Discord, need help to pull me in krub.

_rw#1726

**Review by leomotors — APPROVED** [review]
🙏

**Review by dtinth — APPROVED** [review]

**Pull request merged**
