### PR TITLE
feat: added ProjectThemes enum

### PR DESCRIPTION
**Pull request by Icyscools**
**Always tag `🚀 READY FOR REVIEW` once your PR is Ready to be one of us :)**

This PR is intend to inspires project maintainers to add a custom project theme with a custom icon in a project card.

> 🪄 **DON'T FORGET TO CLAIM YOUR TICKET!** via [Eventpop application form.](https://www.eventpop.me/events/13854/application_forms/845/applicants/new)

### CODE REVIEW

**Review by dtinth — DISMISSED** [review]
LGTM!

**Review by ryanrw — DISMISSED** [review]
Also LGTM!

**Comment by Icyscools** [comment]
I don't know why I can't add tag labels to the PR, but this PR's tag should be `🚀 READY FOR REVIEW` and `Enhancement 🛠`. 😅

Anyway, the latest commit doesn't pass the code style test, so I fixed the code formatting by running `pnpm prettier:write` and push again.

**Review by ryanrw — APPROVED** [review]

**Review by dtinth — APPROVED** [review]
LGTM

**Pull request merged**
