### PR TITLE
Hello from 21Sep

### PR DESCRIPTION
**Pull request by SeenamZaSodaSingha**
**Always tag `🚀 READY FOR REVIEW` once your PR is Ready to be one of us :)**

We value your endeavors to enhance the Hacktoberfest Museum better!

## If (this.PR.category === "The new entry 💫")

**Please tag `The new entry 💫` to the PR in order to categorize yours as the star being recognized by the Museum.**

## Else if (this.PR.category === "Enhancement 🛠")

**Please tag `Enhancement 🛠` to the PR as you're developing the Museum more wonderfully!**

## Finally:

> 🪄 **DON'T FORGET TO CLAIM YOUR TICKET!** via [Eventpop application form.](https://www.eventpop.me/events/13854/application_forms/845/applicants/new)

### CODE REVIEW

**Comment by intaniger** [comment]
@SeenamZaSodaSingha can you please elaborate what you're trying to do here? maybe we can help together.

**Comment by narze** [comment]
Maybe he does not know how typescript works 😂

**Comment by ryanrw** [comment]
Maybe this PR is invalid?

**Comment by intaniger** [comment]
@SeenamZaSodaSingha please answer the question by `Sat Oct 22 2022 23:59:59 GMT+0700 (Indochina Time)`. otherwise we will considered this PR as invalid and close it.

**Comment by ryanrw** [comment]
I'll closed this one due to no response from author.

**Pull request closed without merging**
