### PR TITLE
[Feat] Filter Search

### PR DESCRIPTION
**Pull request by runyasak**
# Scope of work
Add search input to filter projects by `founderName`, `title`, and `topic`

# Screenshots
image

If you have any feedback or suggestion, please do not hesitate to reply on this PR. 😁

### CODE REVIEW

**Review by dtinth — DISMISSED** [review]
LGTM!

**Comment by dtinth** [comment]
@runyasak Sorry, there has been a merge conflict, can you resolve it?

**Review by ryanrw — DISMISSED** [review]

**Comment by ryanrw** [comment]
LGTM 2

**Comment by runyasak** [comment]
@dtinth
I've resolved conflicts from my code.
Please, review my code again. 😁

**Review by dtinth — APPROVED** [review]
Looks great!

**Pull request merged**
